version: 2.1

orbs:
  compare-url: iynere/compare-url@1.2.0

workflows:
  publish-orbs:
    jobs:
      - publish

jobs:
  publish:
    docker:
      - image: circleci/circleci-cli
    steps:
      - checkout
      - compare-url/reconstruct
      - compare-url/use:
          custom-logic: |
            cd packages
            for folder in `git log --format="" --name-only ${CIRCLE_COMPARE_URL##http*/} | cut -d"/" -f1 | sort -u`; do
             echo "contents in $folder were modified"
            done
          step-name: Publish modified orbs