version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: example12
      - image: redis:latest

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ed:9c:0c:76:d9:20:74:82:45:5c:b4:c3:3e:9b:25:5a"

      - checkout:
          post:
            - git fetch --all

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn install --freeze-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn ci:test

      - run: git config --global user.email $GITHUB_EMAIL
      - run: git config --global user.name $GITHUB_USER

      - run: yarn new-version

      - run: git tag
      - run: echo 'export TAG=`git describe --abbrev=0 --tags $(git rev-list --tags --max-count=2) | sed -n 2p`' >> $BASH_ENV
      - run: echo $TAG
      - run: yarn ci:deploy
